import requests
from bs4 import BeautifulSoup
import openpyxl

# Create a new workbook and select the active worksheet
workbook = openpyxl.Workbook()
worksheet = workbook.active

# Add the header row to the worksheet
headers = ["Area", "City", "District", "State", "Pincode"]
worksheet.append(headers)

# Make a request to the webpage and parse the HTML content
# url = "https://www.example.com/page-with-table"  # Replace with the actual URL
# response = requests.get(url)
# soup = BeautifulSoup(response.content, "html.parser")

# Paste the HTML code here
html_code = """<table class="alt"><tbody><tr><th>Office</th><th>Taluk</th><th>District</th><th>State</th><th>Pincode</th></tr>
                                                                        <tr><td><a href="/pincode/gujarat/mahesana/chandrasan">Chandrasan</a></td><td>Kadi</td><td>Mahesana</td><td>GUJARAT</td><td> 382170</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/charol">Charol</a></td><td>Kadi</td><td>Mahesana</td><td>GUJARAT</td><td> 382120</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/khanderaopura">Khanderaopura</a></td><td>Kadi</td><td>Mahesana</td><td>GUJARAT</td><td> 382115</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/rancharada">Rancharada</a></td><td>Kalol</td><td>Mahesana</td><td>GUJARAT</td><td> 382115</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/adraj-merda">Adraj Merda</a></td><td>Kadi</td><td>Mahesana</td><td>GUJARAT</td><td> 382728</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/adundra">Adundra</a></td><td>Kadi</td><td>Mahesana</td><td>GUJARAT</td><td> 382715</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/aglod">Aglod</a></td><td>Vijapur</td><td>Mahesana</td><td>GUJARAT</td><td> 382870</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/agol">Agol</a></td><td>Kadi</td><td>Mahesana</td><td>GUJARAT</td><td> 382165</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/aithor">Aithor</a></td><td>Unjha</td><td>Mahesana</td><td>GUJARAT</td><td> 384170</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/akhaj">Akhaj</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 382710</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/aloda">Aloda</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 384205</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/ambala">Ambala</a></td><td>Becharaji</td><td>Mahesana</td><td>GUJARAT</td><td> 384210</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/ambaliasan">Ambaliasan</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 382732</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/ambasan">Ambasan</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 384435</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/ambavada">Ambavada</a></td><td>Kheralu</td><td>Mahesana</td><td>GUJARAT</td><td> 384335</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/amudh">Amudh</a></td><td>Unjha</td><td>Mahesana</td><td>GUJARAT</td><td> 384170</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/ankaliyara">Ankaliyara</a></td><td>Satlasana</td><td>Mahesana</td><td>GUJARAT</td><td> 384330</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/asjol">Asjol</a></td><td>Becharaji</td><td>Mahesana</td><td>GUJARAT</td><td> 384410</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/badarpur">Badarpur</a></td><td>Vadnagar</td><td>Mahesana</td><td>GUJARAT</td><td> 384355</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/balad">Balad</a></td><td>Kheralu</td><td>Mahesana</td><td>GUJARAT</td><td> 384325</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/balasar">Balasar</a></td><td>Kadi</td><td>Mahesana</td><td>GUJARAT</td><td> 382715</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/balol">Balol</a></td><td>Becharaji</td><td>Mahesana</td><td>GUJARAT</td><td> 384410</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/bamanva">Bamanva</a></td><td>Vijapur</td><td>Mahesana</td><td>GUJARAT</td><td> 384355</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/bamosana">Bamosana</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 384120</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/basana">Basana</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 384001</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/bavlu">Bavlu</a></td><td>Kadi</td><td>Mahesana</td><td>GUJARAT</td><td> 382165</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/becharaji">Becharaji</a></td><td>Becharaji</td><td>Mahesana</td><td>GUJARAT</td><td> 384210</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/bedasma-mumanvas">Bedasma Mumanvas</a></td><td>Satlasana</td><td>Mahesana</td><td>GUJARAT</td><td> 384330</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/bhalak">Bhalak</a></td><td>Visnagar</td><td>Mahesana</td><td>GUJARAT</td><td> 384315</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/bhalusana">Bhalusana</a></td><td>Satlasana</td><td>Mahesana</td><td>GUJARAT</td><td> 384330</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/bhandu">Bhandu</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 384120</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/bhankhar">Bhankhar</a></td><td>Unjha</td><td>Mahesana</td><td>GUJARAT</td><td> 384170</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/bhasaria">Bhasaria</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 382732</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/bhatasan">Bhatasan</a></td><td>Kadi</td><td>Mahesana</td><td>GUJARAT</td><td> 382705</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/bhatvas">Bhatvas</a></td><td>Satalasana</td><td>Mahesana</td><td>GUJARAT</td><td> 384330</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/bhavsor">Bhavsor</a></td><td>Vijapur</td><td>Mahesana</td><td>GUJARAT</td><td> 382870</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/bhesana">Bhesana</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 384421</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/bhimpura">Bhimpura</a></td><td>Satlasana</td><td>Mahesana</td><td>GUJARAT</td><td> 384330</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/bhunav">Bhunav</a></td><td>Unjha</td><td>Mahesana</td><td>GUJARAT</td><td> 384130</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/bilia">Bilia</a></td><td>Vijapur</td><td>Mahesana</td><td>GUJARAT</td><td> 382870</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/bokarwada">Bokarwada</a></td><td>Visnagar</td><td>Mahesana</td><td>GUJARAT</td><td> 384120</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/boriavi">Boriavi</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 384435</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/borisana-kadi">Borisana Kadi</a></td><td>Kadi</td><td>Mahesana</td><td>GUJARAT</td><td> 382728</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/brahmanwada">Brahmanwada</a></td><td>Unjha</td><td>Mahesana</td><td>GUJARAT</td><td> 384215</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/budasan">Budasan</a></td><td>Kadi</td><td>Mahesana</td><td>GUJARAT</td><td> 382715</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/butta-paldi">Butta Paldi</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 384120</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/chada">Chada</a></td><td>Kheralu</td><td>Mahesana</td><td>GUJARAT</td><td> 384325</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/chadasana">Chadasana</a></td><td>Becharaji</td><td>Mahesana</td><td>GUJARAT</td><td> 384210</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/chaluva">Chaluva</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 382732</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/chansol">Chansol</a></td><td>Kheralu</td><td>Mahesana</td><td>GUJARAT</td><td> 384325</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/charadu">Charadu</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 382730</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/chhabalia">Chhabalia</a></td><td>Vadnagar</td><td>Mahesana</td><td>GUJARAT</td><td> 384355</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/chhathiarda">Chhathiarda</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 384205</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/chotia">Chotia</a></td><td>Kheralu</td><td>Mahesana</td><td>GUJARAT</td><td> 384325</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/dabhad">Dabhad</a></td><td>Kheralu</td><td>Mahesana</td><td>GUJARAT</td><td> 384325</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/dabhala">Dabhala</a></td><td>Vijapur</td><td>Mahesana</td><td>GUJARAT</td><td> 382865</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/dabhi">Dabhi</a></td><td>Unjha</td><td>Mahesana</td><td>GUJARAT</td><td> 384170</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/dabhoda">Dabhoda</a></td><td>Kheralu</td><td>Mahesana</td><td>GUJARAT</td><td> 384325</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/dadhial">Dadhial</a></td><td>Visnagar</td><td>Mahesana</td><td>GUJARAT</td><td> 384305</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/dagavadia">Dagavadia</a></td><td>Vijapur</td><td>Mahesana</td><td>GUJARAT</td><td> 382830</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/dalisana">Dalisana</a></td><td>Kheralu</td><td>Mahesana</td><td>GUJARAT</td><td> 384325</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/dangarwa">Dangarwa</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 382705</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/daran">Daran</a></td><td>Kadi</td><td>Mahesana</td><td>GUJARAT</td><td> 382165</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/dasaj">Dasaj</a></td><td>Unjha</td><td>Mahesana</td><td>GUJARAT</td><td> 384170</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/davada">Davada</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 384120</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/davol">Davol</a></td><td>Kheralu</td><td>Mahesana</td><td>GUJARAT</td><td> 384325</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/dedana">Dedana</a></td><td>Becharaji</td><td>Mahesana</td><td>GUJARAT</td><td> 384210</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/dela">Dela</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 384001</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/deloli">Deloli</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 384410</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/delvada-khant">Delvada Khant</a></td><td>Becharaji</td><td>Mahesana</td><td>GUJARAT</td><td> 384210</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/denap">Denap</a></td><td>Visnagar</td><td>Mahesana</td><td>GUJARAT</td><td> 384315</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/dethali">Dethali</a></td><td>Becharaji</td><td>Mahesana</td><td>GUJARAT</td><td> 384210</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/deusana">Deusana</a></td><td>Kadi</td><td>Mahesana</td><td>GUJARAT</td><td> 382715</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/devda">Devda</a></td><td>Vijapur</td><td>Mahesana</td><td>GUJARAT</td><td> 382830</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/devpura">Devpura</a></td><td>Vijapur</td><td>Mahesana</td><td>GUJARAT</td><td> 382870</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/devrasan">Devrasan</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 382710</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/dhamanva">Dhamanva</a></td><td>Visnagar</td><td>Mahesana</td><td>GUJARAT</td><td> 384001</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/dhanali">Dhanali</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 382732</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/dharampur">Dharampur</a></td><td>Kadi</td><td>Mahesana</td><td>GUJARAT</td><td> 382165</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/dharoi-dsc">Dharoi DSC</a></td><td>Satlasana</td><td>Mahesana</td><td>GUJARAT</td><td> 384360</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/dholasan">Dholasan</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 382732</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/diwanpura">Diwanpura</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 384421</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/dodiwada">Dodiwada</a></td><td>Becharaji</td><td>Mahesana</td><td>GUJARAT</td><td> 384210</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/falu">Falu</a></td><td>Vijapur</td><td>Mahesana</td><td>GUJARAT</td><td> 382870</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/fudeda">Fudeda</a></td><td>Vijapur</td><td>Mahesana</td><td>GUJARAT</td><td> 382860</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/fuletra">Fuletra</a></td><td>Kadi</td><td>Mahesana</td><td>GUJARAT</td><td> 382728</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/gadha">Gadha</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 384001</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/gambhu">Gambhu</a></td><td>Becharaji</td><td>Mahesana</td><td>GUJARAT</td><td> 384212</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/ganeshpura">Ganeshpura</a></td><td>Kadi</td><td>Mahesana</td><td>GUJARAT</td><td> 382705</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/ganpat-vidyanagar">Ganpat Vidyanagar</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 384012</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/gavada">Gavada</a></td><td>Vijapur</td><td>Mahesana</td><td>GUJARAT</td><td> 382815</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/gerita-kolavda-rs">Gerita Kolavda RS</a></td><td>Vijapur</td><td>Mahesana</td><td>GUJARAT</td><td> 382820</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/ghantu-dhanpura">Ghantu Dhanpura</a></td><td>Vijapur</td><td>Mahesana</td><td>GUJARAT</td><td> 382870</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/ghumasan">Ghumasan</a></td><td>Kadi</td><td>Mahesana</td><td>GUJARAT</td><td> 382705</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/gorad">Gorad</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 384001</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/gorisana">Gorisana</a></td><td>Kheralu</td><td>Mahesana</td><td>GUJARAT</td><td> 384335</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/gothada">Gothada</a></td><td>Satlasana</td><td>Mahesana</td><td>GUJARAT</td><td> 384330</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/gothva">Gothva</a></td><td>Visnagar</td><td>Mahesana</td><td>GUJARAT</td><td> 384315</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/gozaria">Gozaria</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 382825</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/gundrasan">Gundrasan</a></td><td>Vijapur</td><td>Mahesana</td><td>GUJARAT</td><td> 384355</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/gunja">Gunja</a></td><td>Visnagar</td><td>Mahesana</td><td>GUJARAT</td><td> 384315</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/hadol">Hadol</a></td><td>Satlasana</td><td>Mahesana</td><td>GUJARAT</td><td> 384360</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/hajipur">Hajipur</a></td><td>Vadnagar</td><td>Mahesana</td><td>GUJARAT</td><td> 384170</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/hirpura">Hirpura</a></td><td>Vijapur</td><td>Mahesana</td><td>GUJARAT</td><td> 382870</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/indrad">Indrad</a></td><td>Kadi</td><td>Mahesana</td><td>GUJARAT</td><td> 382715</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/jagnathpura">Jagnathpura</a></td><td>Unjha</td><td>Mahesana</td><td>GUJARAT</td><td> 384140</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/jagudan">Jagudan</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 382710</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/jakasana">Jakasana</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 384421</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/jantral">Jantral</a></td><td>Vijapur</td><td>Mahesana</td><td>GUJARAT</td><td> 382860</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/jasalpur">Jasalpur</a></td><td>Kadi</td><td>Mahesana</td><td>GUJARAT</td><td> 382715</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/jaska">Jaska</a></td><td>Visnagar</td><td>Mahesana</td><td>GUJARAT</td><td> 384315</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/jepur">Jepur</a></td><td>Vijapur</td><td>Mahesana</td><td>GUJARAT</td><td> 382870</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/jeshangpura">Jeshangpura</a></td><td>Kadi</td><td>Mahesana</td><td>GUJARAT</td><td> 382165</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/jetalvasana">Jetalvasana</a></td><td>Visnagar</td><td>Mahesana</td><td>GUJARAT</td><td> 384120</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/jhotana">Jhotana</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 384421</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/jhulasan">Jhulasan</a></td><td>Kadi</td><td>Mahesana</td><td>GUJARAT</td><td> 382705</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/jornang">Jornang</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 382732</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/juni-sedhavi">Juni Sedhavi</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 382705</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/kada-mahesana">Kada Mahesana</a></td><td>Visnagar</td><td>Mahesana</td><td>GUJARAT</td><td> 384305</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/kadi-mkt-yard">Kadi Mkt Yard</a></td><td>Kadi</td><td>Mahesana</td><td>GUJARAT</td><td> 382715</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/kadi">Kadi</a></td><td>Kadi</td><td>Mahesana</td><td>GUJARAT</td><td> 382715</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/kahipur">Kahipur</a></td><td>Vadnagar</td><td>Mahesana</td><td>GUJARAT</td><td> 384355</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/kahoda">Kahoda</a></td><td>Unjha</td><td>Mahesana</td><td>GUJARAT</td><td> 384130</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/kaiyal">Kaiyal</a></td><td>Kadi</td><td>Mahesana</td><td>GUJARAT</td><td> 382705</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/kalri">Kalri</a></td><td>Becharaji</td><td>Mahesana</td><td>GUJARAT</td><td> 384210</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/kalyanpura">Kalyanpura</a></td><td>Kadi</td><td>Mahesana</td><td>GUJARAT</td><td> 382165</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/kamana">Kamana</a></td><td>Visnagar</td><td>Mahesana</td><td>GUJARAT</td><td> 384315</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/kamli">Kamli</a></td><td>Unjha</td><td>Mahesana</td><td>GUJARAT</td><td> 384140</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/kanoda">Kanoda</a></td><td>Becharaji</td><td>Mahesana</td><td>GUJARAT</td><td> 384212</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/kansa">Kansa</a></td><td>Visnagar</td><td>Mahesana</td><td>GUJARAT</td><td> 384315</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/kansarakui">Kansarakui</a></td><td>Visnagar</td><td>Mahesana</td><td>GUJARAT</td><td> 384001</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/kanzari">Kanzari</a></td><td>Kadi</td><td>Mahesana</td><td>GUJARAT</td><td> 382165</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/karannagar">Karannagar</a></td><td>Kadi</td><td>Mahesana</td><td>GUJARAT</td><td> 382715</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/karbatia">Karbatia</a></td><td>Vadnagar</td><td>Mahesana</td><td>GUJARAT</td><td> 384355</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/karjisan">Karjisan</a></td><td>Kadi</td><td>Mahesana</td><td>GUJARAT</td><td> 382705</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/karli">Karli</a></td><td>Unjha</td><td>Mahesana</td><td>GUJARAT</td><td> 384170</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/karsanpura">Karsanpura</a></td><td>Kadi</td><td>Mahesana</td><td>GUJARAT</td><td> 384335</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/kaswa">Kaswa</a></td><td>Kadi</td><td>Mahesana</td><td>GUJARAT</td><td> 382715</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/katosan">Katosan</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 384430</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/kelisana">Kelisana</a></td><td>Vijapur</td><td>Mahesana</td><td>GUJARAT</td><td> 382830</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/keshimpa">Keshimpa</a></td><td>Vadnagar</td><td>Mahesana</td><td>GUJARAT</td><td> 384325</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/khadalpur">Khadalpur</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 384421</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/khambhei">Khambhei</a></td><td>Becharaji</td><td>Mahesana</td><td>GUJARAT</td><td> 384210</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/khandosan">Khandosan</a></td><td>Visnagar</td><td>Mahesana</td><td>GUJARAT</td><td> 384310</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/khanusa">Khanusa</a></td><td>Vijapur</td><td>Mahesana</td><td>GUJARAT</td><td> 382850</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/kharod">Kharod</a></td><td>Vijapur</td><td>Mahesana</td><td>GUJARAT</td><td> 382840</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/kharvada">Kharvada</a></td><td>Visnagar</td><td>Mahesana</td><td>GUJARAT</td><td> 384305</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/khatoda">Khatoda</a></td><td>Vadnagar</td><td>Mahesana</td><td>GUJARAT</td><td> 384355</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/khavad">Khavad</a></td><td>Kadi</td><td>Mahesana</td><td>GUJARAT</td><td> 382165</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/kheralu">Kheralu</a></td><td>Kheralu</td><td>Mahesana</td><td>GUJARAT</td><td> 384325</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/kherva">Kherva</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 384001</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/khodamali">Khodamali</a></td><td>Satlasana</td><td>Mahesana</td><td>GUJARAT</td><td> 384360</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/kolad">Kolad</a></td><td>Kadi</td><td>Mahesana</td><td>GUJARAT</td><td> 382165</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/kot">Kot</a></td><td>Vijapur</td><td>Mahesana</td><td>GUJARAT</td><td> 382870</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/kothasana">Kothasana</a></td><td>Satlasana</td><td>Mahesana</td><td>GUJARAT</td><td> 384330</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/kukarwada">Kukarwada</a></td><td>Vijapur</td><td>Mahesana</td><td>GUJARAT</td><td> 382830</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/kundal">Kundal</a></td><td>Kadi</td><td>Mahesana</td><td>GUJARAT</td><td> 382715</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/kuvasana">Kuvasana</a></td><td>Visnagar</td><td>Mahesana</td><td>GUJARAT</td><td> 384315</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/lacjjadi">Lacjjadi</a></td><td>Visnagar</td><td>Mahesana</td><td>GUJARAT</td><td> 384305</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/ladol">Ladol</a></td><td>Vijapur</td><td>Mahesana</td><td>GUJARAT</td><td> 382840</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/lakhvad">Lakhvad</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 384001</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/langhnaj">Langhnaj</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 382730</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/laxmipura">Laxmipura</a></td><td>Visnagar</td><td>Mahesana</td><td>GUJARAT</td><td> 384315</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/lhor">Lhor</a></td><td>Kadi</td><td>Mahesana</td><td>GUJARAT</td><td> 382165</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/linch">Linch</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 384435</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/lunasan">Lunasan</a></td><td>Kadi</td><td>Mahesana</td><td>GUJARAT</td><td> 382715</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/lunva">Lunva</a></td><td>Kheralu</td><td>Mahesana</td><td>GUJARAT</td><td> 384130</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/machhava">Machhava</a></td><td>Kheralu</td><td>Mahesana</td><td>GUJARAT</td><td> 384130</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/madhasana">Madhasana</a></td><td>Kheralu</td><td>Mahesana</td><td>GUJARAT</td><td> 384335</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/madhi">Madhi</a></td><td>Satlasana</td><td>Mahesana</td><td>GUJARAT</td><td> 382860</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/magroda">Magroda</a></td><td>Visnagar</td><td>Mahesana</td><td>GUJARAT</td><td> 384305</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/maguna">Maguna</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 384410</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/mahervada">Mahervada</a></td><td>Unjha</td><td>Mahesana</td><td>GUJARAT</td><td> 384130</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/mahesana-bazar">Mahesana Bazar</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 384001</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/mahesana">Mahesana</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 384001</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/mahesana-i-e">Mahesana I E</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 384002</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/mahesana-jsm">Mahesana JSM</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 384001</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/mahesana-ongc-colony">Mahesana Ongc Colony</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 384003</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/mahesana-railway-colony">Mahesana Railway Colony</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 384002</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/mahiyal">Mahiyal</a></td><td>Kheralu</td><td>Mahesana</td><td>GUJARAT</td><td> 384325</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/maktupur">Maktupur</a></td><td>Unjha</td><td>Mahesana</td><td>GUJARAT</td><td> 384170</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/malekpur-vad">Malekpur Vad</a></td><td>Vadnabar</td><td>Mahesana</td><td>GUJARAT</td><td> 384355</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/malosan">Malosan</a></td><td>Vijapur</td><td>Mahesana</td><td>GUJARAT</td><td> 382815</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/mandali">Mandali</a></td><td>Vijapur</td><td>Mahesana</td><td>GUJARAT</td><td> 382840</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/mandali">Mandali</a></td><td>Becharaji</td><td>Mahesana</td><td>GUJARAT</td><td> 384130</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/mandropur">Mandropur</a></td><td>Kheralu</td><td>Mahesana</td><td>GUJARAT</td><td> 384325</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/manipur">Manipur</a></td><td>Kadi</td><td>Mahesana</td><td>GUJARAT</td><td> 382728</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/manknaj">Manknaj</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 384421</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/martoli">Martoli</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 384430</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/mathasul">Mathasul</a></td><td>Kadi</td><td>Mahesana</td><td>GUJARAT</td><td> 382705</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/medha">Medha</a></td><td>Kadi</td><td>Mahesana</td><td>GUJARAT</td><td> 382165</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/meghaliasana">Meghaliasana</a></td><td>Visnagar</td><td>Mahesana</td><td>GUJARAT</td><td> 384001</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/meu">Meu</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 382730</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/mevad">Mevad</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 382710</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/mitha">Mitha</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 384001</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/modhera">Modhera</a></td><td>Becharaji</td><td>Mahesana</td><td>GUJARAT</td><td> 384212</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/molipur">Molipur</a></td><td>Vadnagar</td><td>Mahesana</td><td>GUJARAT</td><td> 384355</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/motap">Motap</a></td><td>Becharaji</td><td>Mahesana</td><td>GUJARAT</td><td> 384212</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/moti-bhalu">Moti Bhalu</a></td><td>Satlasana</td><td>Mahesana</td><td>GUJARAT</td><td> 384330</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/moti-dau">Moti Dau</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 384120</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/moti-hirvani">Moti Hirvani</a></td><td>Kheralu</td><td>Mahesana</td><td>GUJARAT</td><td> 384325</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/mudarda">Mudarda</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 384421</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/mulsan">Mulsan</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 382710</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/nadasa">Nadasa</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 384410</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/nagalpur">Nagalpur</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 384001</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/nagrasan">Nagrasan</a></td><td>Kadi</td><td>Mahesana</td><td>GUJARAT</td><td> 382715</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/nandasan">Nandasan</a></td><td>Kadi</td><td>Mahesana</td><td>GUJARAT</td><td> 382705</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/nani-kadi">Nani Kadi</a></td><td>Kadi</td><td>Mahesana</td><td>GUJARAT</td><td> 382715</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/nanivada">Nanivada</a></td><td>Kheralu</td><td>Mahesana</td><td>GUJARAT</td><td> 384325</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/navasangpur">Navasangpur</a></td><td>Vijapur</td><td>Mahesana</td><td>GUJARAT</td><td> 382870</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/nugar">Nugar</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 384205</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/padharia">Padharia</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 382865</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/paladi">Paladi</a></td><td>Visnagar</td><td>Mahesana</td><td>GUJARAT</td><td> 384315</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/palaj">Palaj</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 384410</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/palodar">Palodar</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 384205</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/pamol">Pamol</a></td><td>Vijapur</td><td>Mahesana</td><td>GUJARAT</td><td> 382820</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/panchot">Panchot</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 384205</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/pedhamali">Pedhamali</a></td><td>Vijapur</td><td>Mahesana</td><td>GUJARAT</td><td> 382870</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/piludra">Piludra</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 384001</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/pilvai">Pilvai</a></td><td>Vijapur</td><td>Mahesana</td><td>GUJARAT</td><td> 382850</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/pudgam">Pudgam</a></td><td>Visnagar</td><td>Mahesana</td><td>GUJARAT</td><td> 384310</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/punasan">Punasan</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 382710</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/rajgadh">Rajgadh</a></td><td>Visnagar</td><td>Mahesana</td><td>GUJARAT</td><td> 384315</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/rajpur">Rajpur</a></td><td>Kadi</td><td>Mahesana</td><td>GUJARAT</td><td> 382715</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/ralisana">Ralisana</a></td><td>Visnagar</td><td>Mahesana</td><td>GUJARAT</td><td> 384315</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/rampur-kot">Rampur Kot</a></td><td>Visnagar</td><td>Mahesana</td><td>GUJARAT</td><td> 382870</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/ranasan">Ranasan</a></td><td>Vijapur</td><td>Mahesana</td><td>GUJARAT</td><td> 382870</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/ranchhodpura">Ranchhodpura</a></td><td>Unjha</td><td>Mahesana</td><td>GUJARAT</td><td> 384170</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/ranela">Ranela</a></td><td>Becharaji</td><td>Mahesana</td><td>GUJARAT</td><td> 384212</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/rangakui">Rangakui</a></td><td>Visnagar</td><td>Mahesana</td><td>GUJARAT</td><td> 384315</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/ransipur">Ransipur</a></td><td>Vijapur</td><td>Mahesana</td><td>GUJARAT</td><td> 382870</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/rantej">Rantej</a></td><td>Becharaji</td><td>Mahesana</td><td>GUJARAT</td><td> 384410</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/rasulpur">Rasulpur</a></td><td>Kheralu</td><td>Mahesana</td><td>GUJARAT</td><td> 384325</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/sabalpur">Sabalpur</a></td><td>Vadnagar</td><td>Mahesana</td><td>GUJARAT</td><td> 384355</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/sadra">Sadra</a></td><td>Kadi</td><td>Mahesana</td><td>GUJARAT</td><td> 382715</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/saduthala">Saduthala</a></td><td>Visnagar</td><td>Mahesana</td><td>GUJARAT</td><td> 384315</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/sagthala">Sagthala</a></td><td>Kheralu</td><td>Mahesana</td><td>GUJARAT</td><td> 384325</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/saldi">Saldi</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 382730</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/sametra">Sametra</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 384001</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/sampawada">Sampawada</a></td><td>Becharaji</td><td>Mahesana</td><td>GUJARAT</td><td> 384210</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/sanganpur">Sanganpur</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 382710</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/santhal">Santhal</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 384430</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/sardarpur">Sardarpur</a></td><td>Vijapur</td><td>Mahesana</td><td>GUJARAT</td><td> 384340</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/sardarpur-mahesana">Sardarpur Mahesana</a></td><td>Vijapur</td><td>Mahesana</td><td>GUJARAT</td><td> 382860</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/sarsav">Sarsav</a></td><td>Kadi</td><td>Mahesana</td><td>GUJARAT</td><td> 382715</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/sartanpur">Sartanpur</a></td><td>Satlasana</td><td>Mahesana</td><td>GUJARAT</td><td> 384330</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/sarvoday-ashram">Sarvoday Ashram</a></td><td>Visnagar</td><td>Mahesana</td><td>GUJARAT</td><td> 384310</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/satlasana">Satlasana</a></td><td>Satlasana</td><td>Mahesana</td><td>GUJARAT</td><td> 384330</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/savala">Savala</a></td><td>Visnagar</td><td>Mahesana</td><td>GUJARAT</td><td> 384001</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/shankhalpur">Shankhalpur</a></td><td>Becharaji</td><td>Mahesana</td><td>GUJARAT</td><td> 384210</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/sihi">Sihi</a></td><td>Unjha</td><td>Mahesana</td><td>GUJARAT</td><td> 384170</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/sipor">Sipor</a></td><td>Vadnagar</td><td>Mahesana</td><td>GUJARAT</td><td> 384335</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/sobhasan">Sobhasan</a></td><td>Vadnagar</td><td>Mahesana</td><td>GUJARAT</td><td> 384335</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/sobhasan">Sobhasan</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 384001</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/sokhda">Sokhda</a></td><td>Vijapur</td><td>Mahesana</td><td>GUJARAT</td><td> 382830</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/sudasana">Sudasana</a></td><td>Satlasana</td><td>Mahesana</td><td>GUJARAT</td><td> 384340</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/sujatpura">Sujatpura</a></td><td>Kadi</td><td>Mahesana</td><td>GUJARAT</td><td> 382715</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/sultanpur">Sultanpur</a></td><td>Vadnagar</td><td>Mahesana</td><td>GUJARAT</td><td> 384355</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/sundarpur">Sundarpur</a></td><td>Vijapur</td><td>Mahesana</td><td>GUJARAT</td><td> 382860</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/sundhia">Sundhia</a></td><td>Vadnagar</td><td>Mahesana</td><td>GUJARAT</td><td> 384345</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/sunok">Sunok</a></td><td>Unjha</td><td>Mahesana</td><td>GUJARAT</td><td> 384170</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/suraj">Suraj</a></td><td>Kadi</td><td>Mahesana</td><td>GUJARAT</td><td> 382715</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/surpura">Surpura</a></td><td>Becharaji</td><td>Mahesana</td><td>GUJARAT</td><td> 384210</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/tarabh">Tarabh</a></td><td>Visnagar</td><td>Mahesana</td><td>GUJARAT</td><td> 384310</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/tarangaji-temple">Tarangaji Temple</a></td><td>Satlasana</td><td>Mahesana</td><td>GUJARAT</td><td> 384330</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/tareti">Tareti</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 384001</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/tatosan">Tatosan</a></td><td>Vijapur</td><td>Mahesana</td><td>GUJARAT</td><td> 382820</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/thol">Thol</a></td><td>Kadi</td><td>Mahesana</td><td>GUJARAT</td><td> 382728</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/thol-i-e">Thol I E</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 382728</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/timba">Timba</a></td><td>Satlasana</td><td>Mahesana</td><td>GUJARAT</td><td> 384330</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/titodan">Titodan</a></td><td>Vijapur</td><td>Mahesana</td><td>GUJARAT</td><td> 382865</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/tundali">Tundali</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 382732</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/tundav">Tundav</a></td><td>Unjha</td><td>Mahesana</td><td>GUJARAT</td><td> 384170</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/udalpur">Udalpur</a></td><td>Visnagar</td><td>Mahesana</td><td>GUJARAT</td><td> 384001</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/umari">Umari</a></td><td>Satlasana</td><td>Mahesana</td><td>GUJARAT</td><td> 384340</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/umta">Umta</a></td><td>Visnagar</td><td>Mahesana</td><td>GUJARAT</td><td> 384320</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/unad">Unad</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 384335</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/unava">Unava</a></td><td>Unjha</td><td>Mahesana</td><td>GUJARAT</td><td> 384160</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/undani">Undani</a></td><td>Vadnagar</td><td>Mahesana</td><td>GUJARAT</td><td> 384355</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/undhai">Undhai</a></td><td>Vadnagar</td><td>Mahesana</td><td>GUJARAT</td><td> 384335</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/unjha-kotkuva">Unjha Kotkuva</a></td><td>Unjha</td><td>Mahesana</td><td>GUJARAT</td><td> 384170</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/unjha">Unjha</a></td><td>Unjha</td><td>Mahesana</td><td>GUJARAT</td><td> 384170</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/unjha-umiya-mataji">Unjha Umiya Mataji</a></td><td>Unjha</td><td>Mahesana</td><td>GUJARAT</td><td> 384170</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/untva">Untva</a></td><td>Kadi</td><td>Mahesana</td><td>GUJARAT</td><td> 382715</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/upera">Upera</a></td><td>Unjha</td><td>Mahesana</td><td>GUJARAT</td><td> 384170</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/vadasan">Vadasan</a></td><td>Vijapur</td><td>Mahesana</td><td>GUJARAT</td><td> 382830</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/vadasma">Vadasma</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 382705</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/vadharoda">Vadharoda</a></td><td>Kadi</td><td>Mahesana</td><td>GUJARAT</td><td> 382165</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/vadosan">Vadosan</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 384001</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/vadu">Vadu</a></td><td>Kadi</td><td>Mahesana</td><td>GUJARAT</td><td> 382705</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/vaghawadi">Vaghawadi</a></td><td>Kheralu</td><td>Mahesana</td><td>GUJARAT</td><td> 384335</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/valam">Valam</a></td><td>Visnagar</td><td>Mahesana</td><td>GUJARAT</td><td> 384310</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/valasana">Valasana</a></td><td>Vadnagar</td><td>Mahesana</td><td>GUJARAT</td><td> 384335</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/vamaj">Vamaj</a></td><td>Kadi</td><td>Mahesana</td><td>GUJARAT</td><td> 382728</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/vanagala">Vanagala</a></td><td>Unjha</td><td>Mahesana</td><td>GUJARAT</td><td> 384170</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/varetha">Varetha</a></td><td>Kheralu</td><td>Mahesana</td><td>GUJARAT</td><td> 384325</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/varvada">Varvada</a></td><td>Unjha</td><td>Mahesana</td><td>GUJARAT</td><td> 384215</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/vasai">Vasai</a></td><td>Satlasana</td><td>Mahesana</td><td>GUJARAT</td><td> 384340</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/vasai-dabhala">Vasai Dabhala</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 382865</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/vekra">Vekra</a></td><td>Kadi</td><td>Mahesana</td><td>GUJARAT</td><td> 382165</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/venpura">Venpura</a></td><td>Becharaji</td><td>Mahesana</td><td>GUJARAT</td><td> 384210</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/vidaj">Vidaj</a></td><td>Kadi</td><td>Mahesana</td><td>GUJARAT</td><td> 382715</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/vijapur-bazar">Vijapur Bazar</a></td><td>Vijapur</td><td>Mahesana</td><td>GUJARAT</td><td> 382870</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/vijapur">Vijapur</a></td><td>Vijapur</td><td>Mahesana</td><td>GUJARAT</td><td> 382870</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/vijapurda">Vijapurda</a></td><td>Becharaji</td><td>Mahesana</td><td>GUJARAT</td><td> 384212</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/virsoda">Virsoda</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 384430</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/virta">Virta</a></td><td>Mahesana</td><td>Mahesana</td><td>GUJARAT</td><td> 384001</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/visatpur">Visatpur</a></td><td>Kadi</td><td>Mahesana</td><td>GUJARAT</td><td> 382715</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/vishol">Vishol</a></td><td>Unjha</td><td>Mahesana</td><td>GUJARAT</td><td> 384215</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/visnagar-collageurban">Visnagar CollageUrban</a></td><td>Visnagar</td><td>Mahesana</td><td>GUJARAT</td><td> 384315</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/visnagar-market-yard">Visnagar Market Yard</a></td><td>Visnagar</td><td>Mahesana</td><td>GUJARAT</td><td> 384315</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/visnagar">Visnagar</a></td><td>Visnagar</td><td>Mahesana</td><td>GUJARAT</td><td> 384315</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/visnagar-station-road">Visnagar Station Road</a></td><td>Visnagar</td><td>Mahesana</td><td>GUJARAT</td><td> 384315</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/vithoda">Vithoda</a></td><td>Kheralu</td><td>Mahesana</td><td>GUJARAT</td><td> 384325</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/kanthravi">Kanthravi</a></td><td>Patan</td><td>Mahesana</td><td>GUJARAT</td><td> 384260</td></tr>
                                                                            <tr><td><a href="/pincode/gujarat/mahesana/pali">Pali</a></td><td>Patan</td><td>Mahesana</td><td>GUJARAT</td><td> 384260</td></tr>
                                                            </tbody></table>"""
soup = BeautifulSoup(html_code, "html.parser")

# Find the table element
table = soup.find("table", class_="alt")

# Iterate over the rows (excluding the header row)
for row in table.find_all("tr")[1:]:
    cells = row.find_all("td")
    if cells:
        # Extract the data from each cell
        office = cells[0].a.text if cells[0].a else ""
        city = cells[1].text
        district = cells[2].text
        state = cells[3].text
        pincode = cells[4].text.strip()

        # Add the data as a new row to the worksheet
        worksheet.append([office, city, district, state, pincode])

# Save the workbook to an Excel file
workbook.save("output.xlsx")
print("Data has been saved to output.xlsx")